In [7]:
#리스트
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [9]:
L2 = [True, '2',3.0, 4]
L2

[True, '2', 3.0, 4]

In [12]:
[type(item) for item in L2]

[bool, str, float, int]

In [13]:
for item in L2:
    print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [14]:
import numpy as np

In [15]:
np.array([1,4,5,3])

array([1, 4, 5, 3])

In [16]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [17]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [18]:
np.array([[2,3,4,],[5,6,7],[8,9,'10']])

array([['2', '3', '4'],
       ['5', '6', '7'],
       ['8', '9', '10']], dtype='<U11')

In [19]:
#0 으로 채운 길이 10 의 정수 배열
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#1 로 채운 3*5 배열
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.full((3,5,), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
np.arange(0,20,2)# 앞에 0 은 0 부터
#두번쨰 20 은 20미만 까지
#세번째 2 는 2 배수

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.linspace(0, 1, 5) #0 과 1사이에 일정한 간격을 지닌 다섯개의 값

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.random.random((10))

array([0.2430834 , 0.02841397, 0.39228796, 0.35056036, 0.85931219,
       0.97517349, 0.18317   , 0.36991378, 0.92688087, 0.53942383])

In [31]:
np.random.random((3,3))

array([[0.35130488, 0.56705799, 0.48159981],
       [0.7305283 , 0.09966646, 0.64616093],
       [0.62717406, 0.66408431, 0.62808353]])

In [32]:
np.random.normal(0,1,(3,3))

array([[-0.2091834 ,  0.39411861,  0.52671403],
       [ 0.74528695, -0.92472966,  0.79038078],
       [ 0.55999786, -0.29060694,  0.57857505]])

In [34]:
np.random.randint(0,11,(3,3))#0 과 10 사이의 정수 난수로 구성

array([[7, 0, 3],
       [0, 6, 2],
       [8, 8, 9]])

# NumPy 내장루틴 : 사전 정의된 배열 사용


In [36]:
#사전 정의된 배열
np.eye(3) # 3*3 단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
#NumPy 데이터 타입
bool : 1 바이트로 저장된 bool 값(참 또는 거짓)
int : int64 또는 int32
    

In [50]:
np.random.seed(123)

In [57]:
x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3,4))



In [65]:
np.random.seed(123)
x1 = np.random.randint(10, size=6)# size 는 차원의 갯수를지정한다.
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
x1

array([2, 2, 6, 1, 3, 9])

In [70]:
x3 = np.random.randint(10, size=(3,4,5))

# 배열의 속성 지정


In [74]:
print(x3.ndim)# 차원의 갯수(몇 차원인지 알고 싶을때 사용하는 함수)
print(x3.shape)#각차원의 크기 # 가장 많이 사용함
print(x3.size) #전체 배열의 크기
print(x3.dtype)#데이터 타입
print(x3.itemsize) # 배열 요소의 크기(바이트 단위)
print(x3.nbytes) # 배열의 전체 크기(바이트 단위)
#배열의 속성은 (COMMA를 사용해야한다.)

3
(3, 4, 5)
60
int32
4
240


In [76]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [78]:
print(x1[0])
print(x1[-1])

2
9


In [80]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [82]:
x2[:2, :3] #차원을 갯수로 나타내는 : 클론
#행 3개만 보여주고  열은2개만 보여줘

array([[6, 1, 0],
       [9, 0, 0]])

In [83]:
x2[:, 0 ]

array([6, 9, 3])

In [84]:
x2_sub = x2[:2, :2]
x2_sub

array([[6, 1],
       [9, 0]])

In [86]:
x2_sub[0,0] = 99
x2_sub


array([[99,  1],
       [ 9,  0]])

In [87]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [89]:
x2_sub = x2[:2, :2].copy()
x2_sub

array([[99,  1],
       [ 9,  0]])

In [90]:
x2_sub[0,0]=42
x2_sub

array([[42,  1],
       [ 9,  0]])

In [91]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

## 배열 재구조화(형상변경)

In [94]:
grid = np.arange(1, 10)
x = np.array([1,2,3])
print(grid)
print(x)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [95]:
x.reshape(3,1)



array([[1],
       [2],
       [3]])

In [96]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [100]:
#배열 결합
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])


array([1, 2, 3, 3, 2, 1])

In [101]:
z = [99, 99, 99]
np.concatenate([x,y,z])


array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [103]:
grid = np.array(([1,2,3],[4,5,6]))
#첫번째 축을 따라 연결
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
np.concatenate([grid,grid], axis=1) #두번째 축을 따라 연결
#0 일 경우에는 값그대로 나오고
#1 일 경우에는 한축으로 나옴(?)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [109]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4,]])#한톤?이다
#[]와 ()을 잘 사용해야한다.
#괄호때문에 에러가 많이 난다.
#수직쌓기
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [111]:
y = np.array([[99],[99]])
#수평쌓기
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [112]:
#하나의 배열을 여러개로 분할
x = [1,2,3,99,3,2,1]
x1,x2,x3 = np.split(x, [2,5])
print(x1, x2, x3)

[1 2] [ 3 99  3] [2 1]


In [116]:
grid = np.arange(16). reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [122]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 1.출력지정

In [125]:
x = np.arange(5)
y = np.empty(5) 
np.multiply(x, 10, out = y)
y

array([ 0., 10., 20., 30., 40.])

In [126]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

y = np.zeros(10)
np.power(2, x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [127]:
y = np.zeros(10)
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

## 집계

In [129]:
x = np.arange(1,10)
np.add.reduce(x)

45

In [130]:
np.multiply.reduce(x)

362880

In [132]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [133]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)