In [2]:
import pandas as pd
import copy
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
data = pd.read_csv('data/train.csv', encoding='CP949')
data.head()

custid  gender     총구매액  구매건수  평균구매가격  평균할부개월수  구매브랜드종류  내점일수  수입상품_구매비율  \
0      18       0   680100    15   45340      1.7        9    10       26.7   
1      21       0   353450     9   39272      1.2        6     8       11.1   
2      23       0  5671400    36  157539      2.8       22    16        5.6   
3      26       0  1964000    28   70143      1.4       15    14       39.3   
4      35       0   885000     5  177000      6.0        5     2        0.0   

   주말방문비율  가을_구매건수  겨울_구매건수  봄_구매건수  여름_구매건수  아침_구매건수  저녁_구매건수  점심_구매건수 주구매코너  
0   100.0      NaN      9.0     6.0      NaN      NaN      6.0      9.0   화장품  
1    37.5      NaN      5.0     4.0      NaN      3.0      NaN      6.0  영캐주얼  
2    37.5      7.0     17.0    12.0      NaN     10.0     11.0     15.0   장신구  
3    28.6      5.0      8.0    15.0      NaN      NaN     18.0     10.0   화장품  
4   100.0      NaN      NaN     5.0      NaN      NaN      5.0      NaN   피혁A

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
custid       5000 non-null int64
gender       5000 non-null int64
총구매액         5000 non-null int64
구매건수         5000 non-null int64
평균구매가격       5000 non-null int64
평균할부개월수      5000 non-null float64
구매브랜드종류      5000 non-null int64
내점일수         5000 non-null int64
수입상품_구매비율    5000 non-null float64
주말방문비율       5000 non-null float64
가을_구매건수      4055 non-null float64
겨울_구매건수      4103 non-null float64
봄_구매건수       4311 non-null float64
여름_구매건수      3978 non-null float64
아침_구매건수      3558 non-null float64
저녁_구매건수      4033 non-null float64
점심_구매건수      4855 non-null float64
주구매코너        5000 non-null object
dtypes: float64(10), int64(7), object(1)
memory usage: 703.2+ KB


In [9]:
dataP = data.copy()

In [10]:
dataP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
custid       5000 non-null int64
gender       5000 non-null int64
총구매액         5000 non-null int64
구매건수         5000 non-null int64
평균구매가격       5000 non-null int64
평균할부개월수      5000 non-null float64
구매브랜드종류      5000 non-null int64
내점일수         5000 non-null int64
수입상품_구매비율    5000 non-null float64
주말방문비율       5000 non-null float64
가을_구매건수      4055 non-null float64
겨울_구매건수      4103 non-null float64
봄_구매건수       4311 non-null float64
여름_구매건수      3978 non-null float64
아침_구매건수      3558 non-null float64
저녁_구매건수      4033 non-null float64
점심_구매건수      4855 non-null float64
주구매코너        5000 non-null object
dtypes: float64(10), int64(7), object(1)
memory usage: 703.2+ KB


In [12]:
obj=['주구매코너'] 

In [13]:
dataP[obj].head()

주구매코너
0   화장품
1  영캐주얼
2   장신구
3   화장품
4   피혁A

In [14]:
dataP[obj] = dataP[obj].apply(lambda x: x.astype('category').cat.codes) 
# cat.code : 문자가 범주형으로 바뀌면 생기는 코드
# apply : 각각의 값별로 함수를 적용

In [15]:
dataP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
custid       5000 non-null int64
gender       5000 non-null int64
총구매액         5000 non-null int64
구매건수         5000 non-null int64
평균구매가격       5000 non-null int64
평균할부개월수      5000 non-null float64
구매브랜드종류      5000 non-null int64
내점일수         5000 non-null int64
수입상품_구매비율    5000 non-null float64
주말방문비율       5000 non-null float64
가을_구매건수      4055 non-null float64
겨울_구매건수      4103 non-null float64
봄_구매건수       4311 non-null float64
여름_구매건수      3978 non-null float64
아침_구매건수      3558 non-null float64
저녁_구매건수      4033 non-null float64
점심_구매건수      4855 non-null float64
주구매코너        5000 non-null int8
dtypes: float64(10), int64(7), int8(1)
memory usage: 669.0 KB


In [17]:
dataP[obj].head()

주구매코너
0     24
1     11
2     15
3     24
4     22

In [19]:
dataP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
custid       5000 non-null int64
gender       5000 non-null int64
총구매액         5000 non-null int64
구매건수         5000 non-null int64
평균구매가격       5000 non-null int64
평균할부개월수      5000 non-null float64
구매브랜드종류      5000 non-null int64
내점일수         5000 non-null int64
수입상품_구매비율    5000 non-null float64
주말방문비율       5000 non-null float64
가을_구매건수      4055 non-null float64
겨울_구매건수      4103 non-null float64
봄_구매건수       4311 non-null float64
여름_구매건수      3978 non-null float64
아침_구매건수      3558 non-null float64
저녁_구매건수      4033 non-null float64
점심_구매건수      4855 non-null float64
주구매코너        5000 non-null int8
dtypes: float64(10), int64(7), int8(1)
memory usage: 669.0 KB


In [20]:
dataP.isnull().sum()

custid          0
gender          0
총구매액            0
구매건수            0
평균구매가격          0
평균할부개월수         0
구매브랜드종류         0
내점일수            0
수입상품_구매비율       0
주말방문비율          0
가을_구매건수       945
겨울_구매건수       897
봄_구매건수        689
여름_구매건수      1022
아침_구매건수      1442
저녁_구매건수       967
점심_구매건수       145
주구매코너           0
dtype: int64

In [18]:
dataP.shape

(5000, 18)

### 결측치 제거

In [21]:
dataP_drop = dataP.dropna(subset=['가을_구매건수','겨울_구매건수','봄_구매건수','여름_구매건수','아침_구매건수','저녁_구매건수','점심_구매건수' ])
dataP_drop.shape

(2235, 18)

In [23]:
dataP_drop.isnull().sum()

custid       0
gender       0
총구매액         0
구매건수         0
평균구매가격       0
평균할부개월수      0
구매브랜드종류      0
내점일수         0
수입상품_구매비율    0
주말방문비율       0
가을_구매건수      0
겨울_구매건수      0
봄_구매건수       0
여름_구매건수      0
아침_구매건수      0
저녁_구매건수      0
점심_구매건수      0
주구매코너        0
dtype: int64

### 결측값 대체

<div class="alert alert-block alert-warning">
- strategy="mean": 평균 대체

- strategy="median": 중위수 대체
- strategy="most_frequent":최빈값 대체


In [24]:
con = ['가을_구매건수','겨울_구매건수','봄_구매건수','여름_구매건수','아침_구매건수','저녁_구매건수','점심_구매건수' ]

In [25]:
from sklearn.preprocessing import Imputer
imputer_con = Imputer(strategy="most_frequent")  
imputer_con.fit(dataP[con])

C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)

In [26]:
x = imputer_con.transform(dataP[con]); x

array([[ 1.,  9.,  6., ...,  1.,  6.,  9.],
       [ 1.,  5.,  4., ...,  3.,  1.,  6.],
       [ 7., 17., 12., ..., 10., 11., 15.],
       ...,
       [12.,  6.,  6., ..., 16.,  1., 21.],
       [ 6.,  4.,  2., ...,  1.,  2., 11.],
       [ 6.,  5., 10., ...,  8.,  5., 19.]])

In [27]:
dataP[con] = x
dataP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
custid       5000 non-null int64
gender       5000 non-null int64
총구매액         5000 non-null int64
구매건수         5000 non-null int64
평균구매가격       5000 non-null int64
평균할부개월수      5000 non-null float64
구매브랜드종류      5000 non-null int64
내점일수         5000 non-null int64
수입상품_구매비율    5000 non-null float64
주말방문비율       5000 non-null float64
가을_구매건수      5000 non-null float64
겨울_구매건수      5000 non-null float64
봄_구매건수       5000 non-null float64
여름_구매건수      5000 non-null float64
아침_구매건수      5000 non-null float64
저녁_구매건수      5000 non-null float64
점심_구매건수      5000 non-null float64
주구매코너        5000 non-null int8
dtypes: float64(10), int64(7), int8(1)
memory usage: 669.0 KB


In [28]:
dataP.isnull().sum()

custid       0
gender       0
총구매액         0
구매건수         0
평균구매가격       0
평균할부개월수      0
구매브랜드종류      0
내점일수         0
수입상품_구매비율    0
주말방문비율       0
가을_구매건수      0
겨울_구매건수      0
봄_구매건수       0
여름_구매건수      0
아침_구매건수      0
저녁_구매건수      0
점심_구매건수      0
주구매코너        0
dtype: int64

In [29]:
dataP.shape

(5000, 18)

In [33]:
dfX = dataP.drop(['custid','gender'], axis=1) 

In [34]:
dfy = dataP['gender']

## Cross-Validation ##

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

#model = KNeighborsClassifier()
model = LogisticRegression()
#model = DecisionTreeClassifier()

In [54]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [55]:
scores = cross_val_score(model, dfX, dfy); scores

C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.60767846, 0.61127774, 0.55102041])

In [56]:
print("Mean: {:.3f}\nStd: {:.3f}\nMin: {:.3f}\nMax: {:.3f}".format(
    scores.mean(), scores.std(), scores.min(), scores.max()))
# 분산이 작으면 Overfitting 이 적다

Mean: 0.590
Std: 0.028
Min: 0.551
Max: 0.611


### 남녀 비율 조정

In [57]:
dataP['gender'].value_counts()

0    3479
1    1521
Name: gender, dtype: int64

- SMOTE + Tomek

In [65]:
#!pip install imblearn

In [ ]:
#from imblearn.combine import *

In [67]:
from imblearn.combine import SMOTETomek

In [ ]:
scores = cross_val_score(model, dfX, dfy); scores

In [68]:
XX, yy = SMOTETomek(random_state=0).fit_sample(dfX, dfy)

In [71]:
scores = cross_val_score(model, XX, yy); scores

C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\700-00\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.57135576, 0.54387755, 0.48673469])